#/bin/bash

# this scripts:
# 1 - launches CEM 
# it uses BellmanVauesOUT.csv or cuts.txt generated by SSV, which have
# to be present in ${INSTANCE}/



# run investment solver
source ${INCLUDE}/cem.sh


