#/bin/bash

# this scripts:
# 2 - launches SIM 
# it uses BellmanVauesOUT.csv or cuts.txt generated by SSV, which have
# to be present in ${INSTANCE}


# run simulations using sddp_solver
source ${INCLUDE}/sim.sh
# alternative: run simulations using investment_solver
#source scripts/include/simCEM.sh

